SELECT * FROM CUSTOMER
ORDER BY CUSTOMERNAME

SELECT * FROM CUSTOMER
ORDER BY CITY, CUSTOMERNAME

SELECT * FROM CUSTOMER
ORDER BY CITY DESC, CUSTOMERNAME ASC

SELECT * FROM CUSTOMER
ORDER BY CITY DESC, BIRTHDATE

SELECT * FROM CUSTOMER
ORDER BY 6,3
 