SELECT * FROM CUSTOMER WHERE CITY='ISTANBUL'
SELECT * FROM CUSTOMER WHERE CUSTOMERNAME LIKE 'HÜSEYİN%'

SELECT * FROM CUSTOMER WHERE CITY='ISTANBUL' AND CUSTOMERNAME LIKE 'HÜSEYİN%'

SELECT * FROM CUSTOMER WHERE CITY='ISTANBUL' OR CUSTOMERNAME LIKE 'HÜSEYİN%'

SELECT * FROM CUSTOMER WHERE CITY='ISTANBUL' AND 1<>1

SELECT * FROM CUSTOMER WHERE CITY='ISTANBUL' OR 1<>1