SELECT * FROM CUSTOMER 
WHERE CUSTOMERNAME='Salih FAYDALI'

SELECT * FROM CUSTOMER 
WHERE ID=18

SELECT * FROM CUSTOMER 
WHERE CITY='İstanbul'

SELECT * FROM CUSTOMER 
WHERE BIRTHDATE='19971024'

SELECT * FROM CUSTOMER 
WHERE CITY='Rize' AND DISTRICT='Pazar / Rize' 

SELECT * FROM CUSTOMER 
WHERE CITY='Rize' AND DISTRICT<>'Pazar / Rize' 

SELECT * FROM CUSTOMER 
WHERE AGE>78

SELECT * FROM CUSTOMER 
WHERE AGE<27

SELECT * FROM CUSTOMER 
WHERE CUSTOMERNAME='Salih FAYDALI'

SELECT * FROM CUSTOMER 
WHERE ID=18

SELECT * FROM CUSTOMER 
WHERE CITY='İstanbul'

SELECT * FROM CUSTOMER 
WHERE BIRTHDATE='19971024'

SELECT * FROM CUSTOMER 
WHERE CITY='Rize' AND DISTRICT='Pazar / Rize' 

SELECT * FROM CUSTOMER 
WHERE CITY='Rize' AND DISTRICT<>'Pazar / Rize' 

SELECT * FROM CUSTOMER 
WHERE BIRTHDATE>='19980101'

SELECT * FROM CUSTOMER 
WHERE AGE BETWEEN 27 AND 33

SELECT * FROM CUSTOMER 
WHERE AGE>=27 AND AGE<=33

SELECT * FROM CUSTOMER
WHERE BIRTHDATE BETWEEN '19980101' AND '19981231'

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'Rümeysa İncedal'

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'Rümeysa%'

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'Kevser%' --Selects records where CUSTOMERNAME starts with "Kevser".

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE '%İNCE%' --Selects records where CUSTOMERNAME contains "İNCE" anywhere.

SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE '%ÖRNEK' --Selects records where CUSTOMERNAME ends with "ÖRNEK".

SELECT * FROM CUSTOMER
WHERE CITY='Isparta'

SELECT * FROM CUSTOMER
WHERE CITY='Isparta'
AND DISTRICT IN ('ULUBORLU', 'YALVAÇ')

SELECT * FROM CUSTOMER
WHERE CITY='Isparta'
AND DISTRICT NOT IN ('ULUBORLU', 'YALVAÇ')
AND GENDER='K'