SELECT * FROM SALES WHERE BRANCH='Kocaeli Subesi'

SELECT SUM(LINENET) AS SATIRSAYISI FROM SALES WHERE BRANCH='Kocaeli Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES WHERE BRANCH='Kocaeli Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI, MIN(LINENET) AS MINFIYAT, MAX(LINENET) MAXFIYAT FROM SALES WHERE BRANCH='Kocaeli Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI, MIN(LINENET) AS MINFIYAT, MAX(LINENET) MAXFIYAT FROM SALES WHERE BRANCH='İstanbul Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI, MIN(LINENET) AS MINFIYAT, MAX(LINENET) MAXFIYAT, AVG(LINENET) AS ORTALAMASATISFIYATI FROM SALES WHERE BRANCH='İstanbul Subesi'

SELECT SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI FROM SALES WHERE BRANCH='Malatya Subesi'

SELECT
[BRANCH],
SUM(LINENET) AS TOPLAMSATIS, 
COUNT(*) AS SATIRSAYISI, 
MIN(LINENET) AS MINFIYAT, 
MAX(LINENET) MAXFIYAT, 
AVG(LINENET) AS ORTALAMASATISFIYATI
FROM SALES 
GROUP BY BRANCH