SELECT U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR2, C.CITY, T.TOWN, D.DISTRICT, A.ADDRESSTEXT
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID

WHERE U.ID=1