--Bir mağazanın gün bazlı satış rakamları

SELECT BRANCH SUBE, DATE_ TARIH, SUM(LINENET) TOPLAMSTAIS, COUNT(*) SATIRSAYISI
FROM SALES 
GROUP BY BRANCH, DATE_
ORDER BY BRANCH, DATE_


SELECT BRANCH SUBE, DATE_ TARIH, SUM(LINENET) TOPLAMSTAIS, COUNT(*) SATIRSAYISI
FROM SALES 
WHERE BRANCH='Malatya Subesi' --AND DATE_='2017-01-05'
GROUP BY BRANCH, DATE_
ORDER BY DATE_

SELECT * FROM SALES WHERE BRANCH='Malatya Subesi' ORDER BY DATE_