--En çok satış yapılan müşteriler

SELECT U.USERNAME_, U.NAMESURNAME,
SUM(BD.TOTAL) AS TOTAL
FROM
USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
GROUP BY U.USERNAME_,U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC

--En çok satış yapılan 10 müşteri

SELECT TOP 10 U.USERNAME_, U.NAMESURNAME,
SUM(BD.TOTAL) AS TOTAL
FROM
USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
GROUP BY U.USERNAME_,U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC