--Ürün kategorilerine göre satış rakamları

SELECT CATEGORY_NAME1, BRAND, SUM(LINENET) FROM 
SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND CATEGORY_NAME1='Gıda'
GROUP BY CATEGORY_NAME1, BRAND
ORDER BY SUM(LINENET) DESC