--Hangi ?ehirde kaç kullan?c? var

SELECT 
C.CITY, COUNT(U.ID)
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
GROUP BY C.CITY ORDER BY 2 DESC

SELECT U.ID, U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD, U.EMAIL AS EMAIL, 
U.TELNR1 AS TELEFON1, U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRESSAYISI, COUNT(DISTINCT C.CITY) AS SEHIRSAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
GROUP BY U.ID, U.USERNAME_, U.NAMESURNAME, U.EMAIL, U.TELNR1, U.TELNR2
HAVING COUNT(A.ID)<>COUNT(DISTINCT C.CITY)



