SELECT * FROM USER_ WHERE ID=1278

SELECT * FROM ADDRES WHERE ID=3169

SELECT * FROM ITEM WHERE ID=13454

SELECT * FROM BASKET

SELECT * FROM BASKETDETAIL

SELECT * FROM PAYMENT

SELECT * FROM ORDER_

SELECT * FROM ORDERDETAIL

SELECT * FROM INVOICE

SELECT * FROM INVOICEDETAIL