-- Ocak 2025'de alışveriş yapan kadın ve erkek müşteriler

SELECT U.GENDER, SUM(BD.TOTAL) AS TOTAL
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID

WHERE B.CREATEDDATE BETWEEN '2025-01-01' AND '2025-01-31'
GROUP BY U.GENDER

