SELECT BRANCH, SUM(LINENET) AS TOPLAMSATIS
FROM SALES 
GROUP BY BRANCH ORDER BY SUM(LINENET) DESC

SELECT TOP 10 BRANCH, SUM(LINENET) AS TOPLAMSATIS
FROM SALES 
GROUP BY BRANCH ORDER BY SUM(LINENET) DESC

SELECT TOP 10 BRANCH, SUM(LINENET) AS TOPLAMSATIS
FROM SALES 
GROUP BY BRANCH ORDER BY 2 DESC