--SUBQUERY ile müşteri bilgisi getirme

SELECT ID, NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) AS BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS ITEMCOUNT_,
(
SELECT ITEMNAME FROM ITEM WHERE ID IN 
	(
		SELECT TOP 1 ITEMID FROM BASKETDETAIL WHERE BASKETID IN
			(
				SELECT ID FROM BASKET WHERE USERID=U.ID
			) ORDER BY DATE_ DESC
	)
) AS LASTITEMNAME
FROM USER_ U
WHERE
(sELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) > 0