--Bir müşterinin gittiği mağaza sayısı

SELECT CLIENTNAME, COUNT(DISTINCT BRANCH)
FROM SALES
GROUP BY CLIENTNAME

SELECT * FROM SALES WHERE CLIENTNAME='Abdulkadir Bilcan'

SELECT DISTINCT BRANCH FROM SALES WHERE CLIENTNAME='Kezban Cihanoglu'

SELECT CLIENTNAME, COUNT(DISTINCT BRANCH)
FROM SALES
GROUP BY CLIENTNAME
HAVING COUNT(DISTINCT BRANCH)>10

SELECT CLIENTNAME, COUNT(DISTINCT BRANCH)
FROM SALES
GROUP BY CLIENTNAME
HAVING COUNT(DISTINCT BRANCH)>10
SELECT DISTINCT BRANCH FROM SALES
WHERE CLIENTNAME='Arzu Alper'