--Ürün markasına göre satışlar

SELECT BRAND, CATEGORY_NAME1, CATEGORY_NAME2, SUM(LINENET) FROM 
SALES
WHERE BRAND IS NOT NULL AND BRAND='Ülker'
GROUP BY BRAND, CATEGORY_NAME1, CATEGORY_NAME2
ORDER BY BRAND, CATEGORY_NAME1, CATEGORY_NAME2 DESC